#!/usr/bin/env bash
#fizzbuzz! FizzBuzz when the number is a multiple of 3 and 5, Fizz when 3, and Buzz when 5. Display number if not.


for n in {1..100}
do
	if [ $((n%3)) = 0 ]
	then
		echo "Fizz"
	
	elif [ $((n%5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$n"
	fi
	if [ $((n%3)) = 0 ] && [ $((n%5)) = 0 ]
	then 
		echo "FizzBuzz"
	fi
	sleep 1
done
