#!/usr/bin/env bash
#display the content of the file /etc/passwd. only display the username, user id, and home directory path for the user.
while read -r Lines
do
	echo "$Lines" | cut -d ":" -f 1,3,5
done < /etc/passwd
