#!/usr/bin/env bash
#This is a script that displays the content of the file /etc/password using the while loop and IFS
FILE="/etc/passwd"
while IFS=: read -r username _ userid groupid useridinfo homedir command
do
   	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $command. $userid's place is protected by the passcode x, more info about the user here: $useridinfo"
done < $FILE       
