#!/usr/bin/env bash
#this is a script saying best school and hi
x=1
while [ $x -lt 9 ]
do
	echo "Best School"
	x=$((x+1))

if [ $x = 9 ]
then
	echo "Best School"
	echo "Hi"
	echo "Best School"
fi
done	
