#!/usr/bin/env bash
#this is a clock script
min=0
hour=0
while [ $hour -lt 13 ]
do
	if [ $min = 0 ]
	then
		echo "Hour $hour"
		min=$((min+1))
	elif [ $min -lt 60 ]
	then
		echo "$min"
		min=$((min+1))
	elif [ $min = 60 ]
	then
		min=0
		hour=$((hour+1))
	fi
done
