#!/usr/bin/env bash
#This will give info about school file
if [ -e school ] 
then 
	echo "school file exists"
else
	echo "school file does not exist"
fi

if [ -e school ] && [ -s school ]
then
	echo "school file is not empty"
elif [ -e school ] && [ ! -s school ]
then
	echo "school file is empty"
fi

if [ -e school ] && [ -f school ]
then
	echo "school file is a regular file"
fi
