#!/usr/bin/env bash
#This will give info about school file
if [ ! -e school ] 
then 
	echo "school file does not exist"
fi
if [-e school ]
then
	if [ -s school ]
	then
		echo "school file is not empty"
	else
		echo "school file is not empty"
	fi
	if [ -f school ]
		echo "school is a regular file"
	fi
else
	echo "school file exists"
fi
