#!/usr/bin/env bash
#This will give info about school file
if [ -f /school ]
then 
	echo "school file exists"
else
	echo "school file does not exist"
fi
if [ -f /school ] && [-s /school]
then
	echo "school file is not empty"
else
	echo "school file is empty"
	 
