#!/usr/bin/env bash
#too much stuff
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love ?!" SIGINIT
trap "rm /var/run/myscript.pid" SIGQUIT
trap "rm /var/run/myscript.pid" SIGTERM
touch "$$" >> /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
done
