#!/usr/bin/env bash
#too much stuff
echo "$$" >> /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
done

trap "echo I hate the kill command;" SIGTERM

trap "echo Y U no love me?!;" SIGINIT 

trap "rm /var/run/myscript.pid;" SIGQUIT

trap rm /var/run/myscript.pid SIGTERM
